In [90]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
%matplotlib inline

In [112]:
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\1632300362534233 (2).csv")

# take a look at the dataset
df.head()
df.dropna(subset=['Address'], inplace=True)

In [113]:
features = ['Area', 'Room', 'Parking']

for col in features:
    mask = df[col].astype(str).str.contains(',', regex=False, na=False)

    if mask.any():
        print("Problem in column:", col)
        display(
            df.loc[
                mask,
                ['Area', 'Room', 'Parking', 'Price(USD)']
            ]
        )

Problem in column: Area

                  Area  Room  Parking  Price(USD)
570     3,310,000,000      2     True   110333.33
709    16,160,000,000      3     True   538666.67
807             1,000      2     True   233333.33
1604    8,400,000,000      2     True   290000.00
2171            3,600      2    False   324000.00
2802    2,550,000,000      2     True    85000.00

In [114]:
df['Parking'] = df['Parking'].astype(int)
df['Elevator'] = df['Elevator'].astype(int)
df['Warehouse'] = df['Warehouse'].astype(int)

df['Area'] = df['Area'].str.replace(',', '')
df.drop([570, 1604, 2171,2802,807,709], inplace=True)

In [115]:
cdf = df[['Area', 'Room', 'Parking', 'Address','Warehouse','Elevator', 'Price(USD)']].copy()

cdf['Area'] = cdf['Area'].astype(int)
cdf['Room'] = cdf['Room'].astype(int)
cdf['Parking'] = cdf['Parking'].astype(int)

cdf = pd.get_dummies(
    cdf,
    columns=['Address'],
    drop_first=True,
    dtype=int
)

cdf.head()

,Area,Room,Parking,Warehouse,Elevator,Price(USD),Address_Abbasabad,Address_Absard,Address_Abuzar,Address_Afsarieh,...,Address_Waterfall,Address_West Ferdows Boulevard,Address_West Pars,Address_Yaftabad,Address_Yakhchiabad,Address_Yousef Abad,Address_Zafar,Address_Zaferanieh,Address_Zargandeh,Address_Zibadasht
0,63,1,1,1,1,61666.67,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,60,1,1,1,1,61666.67,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,79,2,1,1,1,18333.33,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,95,2,1,1,1,30083.33,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,123,2,1,1,1,233333.33,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [128]:
msk = np.random.rand(len(df)) < 0.9
train = cdf[msk]
test = cdf[~msk]

In [129]:
X_train = train.drop(columns=['Price(USD)'])
y_train = train['Price(USD)']

X_test = test.drop(columns=['Price(USD)'])
y_test = test['Price(USD)']

In [130]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# The coefficients
print ('Coefficients: ', regr.coef_)
print("Intercept:", regr.intercept_)

Coefficients:  [ 2.39528636e+03  1.29418067e+04 -2.04869626e+04  2.45086276e+03
 -1.01337249e+04 -4.71482911e+04 -1.09485093e+06 -8.77578478e+04
 -1.24353356e+05 -8.24595154e+04 -9.84744401e+04  1.42921296e+05
 -1.10629628e+05 -1.38295682e+05 -3.05958989e+04 -1.06375521e+05
 -1.08514570e+05 -1.84337951e+05  1.82249325e+05 -2.59571424e+04
  9.89977759e+04 -1.56360683e+05 -1.59582773e+05 -9.44502628e+04
 -9.70380439e+04 -2.08280817e+05 -1.29796390e+05 -1.72425736e+05
 -1.08896713e+05 -1.24719534e+05 -6.69647126e+04 -1.63455684e+05
 -3.21419299e+05 -8.51024252e+04  1.54868687e+04 -5.23924234e+05
 -5.80371032e+03 -5.74333303e+04 -2.22239030e+04 -1.39473917e+05
 -1.31250339e+05  5.77810721e+04 -9.95122849e+04  2.09198989e+05
 -7.47507287e+04 -7.04827632e+04 -3.28353230e+04  8.12360366e+03
  3.74067318e+05 -9.69046569e+04 -9.51680158e+04 -1.62010555e+05
 -6.78454039e+04 -9.75561137e+04  2.56769499e+05 -1.18681352e+05
 -7.94134025e+04 -1.60543487e+05 -1.72767734e+05  1.10509162e+06
 -2.14690321e+04  2.46544881e+04 -1.47138388e+05  1.45693560e+04
 -4.45349668e+03 -4.45313078e+04 -1.57759456e+05 -1.64993870e+05
 -1.08883845e+05 -7.81719612e+04 -1.07391189e+05  2.96888847e+04
 -4.93103612e+04 -1.70879562e+05 -1.20312114e+05 -1.64317888e+05
 -2.22716848e+05 -1.27771587e+05 -1.01459387e+05 -5.56803870e+04
 -1.76025028e+05  2.35492873e+05 -9.43856574e+04 -9.15904294e+04
 -1.22492690e+05 -1.18633395e+05 -2.34526609e+05 -8.63534620e+04
 -9.00365572e+04 -1.11695966e+05 -9.04604985e+04  5.77319508e+05
 -8.38564201e+04 -6.98116537e+04  2.43655975e+05 -1.58489569e+05
 -1.45935803e+05 -3.57295175e+04 -1.40413378e+05 -2.10576901e+05
 -7.92732798e+04  4.42970684e+04 -8.45013485e+04 -1.42872732e+05
 -6.17012279e+04 -1.74259693e+05 -1.17913733e+05 -7.61360975e+04
 -1.14175273e+05  2.38984628e+05 -3.28060188e+04 -1.64397466e+05
 -7.88097700e+04 -6.90967217e+04 -8.72244459e+04 -1.00342810e+05
 -8.86803841e+03 -2.30847632e+05 -1.86560706e+05 -1.73743829e+05
 -9.37962570e+04 -1.89708772e+05  4.34577057e+03 -1.53595525e+05
 -9.69089980e+04 -1.74046732e+05 -6.31839959e+04 -9.79562256e+04
 -1.92678341e+05 -9.63068879e+04 -1.31597603e+05 -1.13184860e+05
 -1.32165482e+05 -4.67396472e+04 -3.36513040e-10 -1.35130448e+05
 -1.13422098e+05 -1.10329233e+05 -2.17307095e+05  2.31782621e+04
 -2.41803436e+05 -1.02952524e+05 -1.60788407e+05 -1.94678591e+05
 -2.40607845e+05 -9.54681569e+04 -9.16012595e+04 -8.58366566e+04
 -1.04305665e+05 -4.08805771e+05 -9.00928790e+04 -1.17165654e+05
 -1.11177843e+05 -1.36996401e+05  8.16809430e+04 -2.11268353e+05
 -1.75697020e+05 -1.87484585e+05 -1.07529296e+05 -3.39185447e+04
 -7.82117142e+04 -1.77170575e+05 -8.42656617e+04 -9.24357874e+04
 -9.79026784e+04 -6.48876052e+04 -2.27079628e+05 -6.97225132e+04
 -5.94889348e+04 -7.21049230e+04 -7.10339918e+04 -1.09733523e+05
 -1.05746178e+05 -1.20252007e+05 -1.27013137e+05 -1.53377536e+05
 -9.09229767e+04 -9.04830836e+04 -6.87627983e+04 -1.92325883e+05
 -1.17984886e+05  5.60028287e+05 -1.71039663e+06  2.85908503e+05
 -1.17084710e-07 -9.80946229e+04 -1.17600752e+05 -6.40378470e+04
 -9.39179905e+04 -1.43572053e+05 -1.37015640e+05 -3.31139611e+04
  2.16743505e+04  3.34763055e+05 -3.97033054e+04 -1.12097314e+05]
Intercept: -16074.406463702588

In [131]:
y_hat = model.predict(X_test)

print(
    "Residual sum of squares: %.2f"
    % np.mean((y_hat - y_test) ** 2)
)

print(
    "Variance score: %.2f"
    % regr.score(X_test, y_test)
)

Residual sum of squares: 19582058995.91
Variance score: 0.70